# Generated by Django 5.2.5 on 2025-08-11 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('claim_settlement', 'Claim Settlement'), ('policy_terms', 'Policy Terms & Conditions'), ('premium_issues', 'Premium Issues'), ('service_quality', 'Service Quality'), ('agent_conduct', 'Agent Conduct'), ('documentation', 'Documentation Issues'), ('fraud_concern', 'Fraud Concern'), ('other', 'Other')], max_length=20)),
                ('complainant_name', models.CharField(max_length=100)),
                ('complainant_email', models.EmailField(max_length=254)),
                ('complainant_phone', models.CharField(max_length=20)),
                ('policy_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('pending_response', 'Pending Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sla_deadline', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='companies.insurancecompany')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grievances.grievance')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance Document',
                'verbose_name_plural': 'Grievance Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='grievances.grievance')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance Message',
                'verbose_name_plural': 'Grievance Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('assign', 'Assigned'), ('status_change', 'Status Changed'), ('message_sent', 'Message Sent'), ('file_upload', 'File Uploaded')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='grievances__user_id_cb5c8c_idx'), models.Index(fields=['model_name'], name='grievances__model_n_e9d737_idx'), models.Index(fields=['timestamp'], name='grievances__timesta_97f208_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['grievance_id'], name='grievances__grievan_acdf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status'], name='grievances__status_6af4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['priority'], name='grievances__priorit_699038_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['insurance_company'], name='grievances__insuran_9f0923_idx'),
        ),
    ]
